package com.logistics.snowapi.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Entity class representing a user within the system. This class is mapped to the 'snow_user' table
 * in the database and includes properties and relationships that define a user and their associated
 * geographic boundaries.
 * <p>
 * This class maintains a many-to-many relationship with {@link Boundary} entities, indicating the geographic
 * boundaries that a user is associated with. This relationship is managed through a join table
 * automatically handled by JPA based on the defined mapping.
 * <p>
 * Attributes:
 * <ul>
 *     <li>{@code id} - The primary key of the user, generated by a sequence in the database.</li>
 *     <li>{@code boundaries} - A set of {@link Boundary} entities that the user is associated with,
 *     representing the geographic areas relevant to the user.</li>
 * </ul>
 * <p>
 * Usage:
 * Instances of this class are used to manage user data within the application, particularly in relation
 * to the geographic boundaries they are associated with. This enables functionalities such as user-specific
 * access control, personalization of geographic data, and management of user permissions regarding
 * geographic regions.
 *
 * @see Boundary
 */
@Getter
@Setter
@Entity
@Table(name = "snow_user")
public class SnowUser {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_id_seq")
    @SequenceGenerator(name = "user_id_seq", sequenceName = "snow_user_user_id_seq", allocationSize = 1)
    @Column(name = "user_id", nullable = false)
    private Integer id;

    @ManyToMany(mappedBy = "snowUsers")
    private Set<Boundary> boundaries = new LinkedHashSet<>();
}